apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
data:
  my.cnf: |
    [mysqld]
    sql_mode = "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    max_connections = 200
    innodb_buffer_pool_size = 128M
    log_bin_trust_function_creators = 1
