apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  dbRootPassword: {{ .Values.secrets.dbRootPassword | b64enc }}
  dbName: {{ .Values.secrets.dbName | b64enc }}
  dbUser: {{ .Values.secrets.dbUser | b64enc }}
  dbPassword: {{ .Values.secrets.dbPassword | b64enc }}
