replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

storage:
  size: 10Gi
  className: standard

secrets:
  dbRootPassword: rootPassword
  dbName: mydb
  dbUser: user
  dbPassword: password

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
