replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

storage:
  size: 10Gi
  className: standard

secrets:
  dbRootPassword: rootPassword
  dbName: mydb
  dbUser: user
  dbPassword: password

storageClass:
  name: standard
  annotations:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "mysql"
    meta.helm.sh/release-namespace: "my-app"

mysqlUrl: "mysql://user:password@mysql-service.my-app.svc.cluster.local:3306/mydb"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
