replicaCount: 2

image:
  repository: oz23/photos-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

database:
  host: "{{ .Release.Name }}-mysql"
  port: "3306"
  user: "user"
  password: "password"
  name: "mydb"

  dbRootPassword: rootPassword
  dbName: mydb
  dbUser: user
  dbPassword: password

s3:
  bucket: "final-project-technion-2468"
  region: "us-east-1"


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
