replicaCount: 2 # Number of application replicas

image:
  repository: oz23/pyui # Docker image for the application
  tag: v1
  pullPolicy: IfNotPresent # Pull image only if not available locally

service:
  type: NodePort # Expose service externally with a NodePort
  port: 80 # Application port

database:
  host: "{{ .Release.Name }}-mysql" # MySQL hostname
  port: "3306" # MySQL port
  user: "user" # Database user
  password: "password" # Database password
  name: "mydb" # Database name

secrets:
  dbRootPassword: rootPassword # MySQL root password
  dbName: mydb # Database name
  dbUser: user # Database user
  dbPassword: password # Database password

s3:
  bucket: "final-project-technion-24688" # S3 bucket for the project
  region: "us-east-1" # AWS region

resources: {} # Resource requests and limits for the application pods

nodeSelector: {} # Node selection criteria

tolerations: [] # Tolerations for scheduling pods on nodes

affinity: {} # Pod affinity rules
