name: CD
on:
  workflow_dispatch:
    inputs:
      EC2_IP:
        description: "The IP address of the Kind EC2 instance"
        required: true

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code # Clone the repository
        uses: actions/checkout@v3

      - name: Copy Repo to Kind EC2
        run: |
          # Save the SSH private key to a file
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 400 key.pem

          # Use rsync to copy the repository, excluding key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" --exclude 'key.pem' ./ ec2-user@${{ inputs.EC2_IP }}:~/repo

      - name: Deploy to Kind Cluster
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ inputs.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Install Helm
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

            # Deploy MySQL Helm chart
            helm upgrade --install mysql ~/repo/helm-charts/mysql \
              --namespace my-app \
              --create-namespace \
              --values ~/repo/helm-charts/mysql/values.yaml

            # Wait for MySQL to become available
            kubectl wait --namespace my-app \
              --for=condition=ready pod \
              --selector=app.kubernetes.io/name=mysql \
              --timeout=300s

            # Deploy Application Helm chart
            helm upgrade --install application ~/repo/helm-charts/application \
              --namespace my-app \
              --values ~/repo/charts/application/values.yaml
